### PR TITLE
Localization of static resource files such as js css fonts; add produ…

### PR DESCRIPTION
**Pull request by atompi**
…ction-ready docker-compose.yml

## Description

Localization of static resource files such as js css fonts; add production-ready docker-compose.yml.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code _(if tests is required for my changes)_
- [ ] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by tarampampam** [comment]
Thanks for your pr! But I think that moving assets under the git is not a good solution. What's the reason?

**Comment by tarampampam** [comment]
I'm very sorry, but I cannot accept this PR. The reasons are:

- Web assets should be loaded directly from the CDN (as of now) or bundled into a single js file using WebPack, for example
- Existing docker-compose file is for development already, and I suppose a separate file for this is not needed

But anyway, you can develop your fork! And thanks for your time!

**Comment by atompi** [comment]
> I'm very sorry, but I cannot accept this PR. The reasons are:
> 
> * Web assets should be loaded directly from the CDN (as of now) or bundled into a single js file using WebPack, for example
> * Existing docker-compose file is for development already, and I suppose a separate file for this is not needed
> 
> But anyway, you can develop your fork! And thanks for your time!

But some users who cannot connect to the Internet may not be able to use this program because they cannot get the CDN resources. Committing CDN resources to a git repository may not be an elegant way to handle this. A model that does not rely on CDNs is obviously more widely used.

I will continue to develop the fork repository for a more suitable solution, such as npm, and I will submit the most suitable version to you at that time.

**Comment by tarampampam** [comment]
Could you please make an issue in this repo with your assets building suggestion? I will try to make all required changes shortly

**Comment by atompi** [comment]
> Could you please make an issue in this repo with your assets building suggestion? I will try to make all required changes shortly

The issue is created [here](https://github.com/tarampampam/webhook-tester/issues/148)

**Pull request closed without merging**
